### ISSUE TITLE
getting this error in docker-compose file during build

### ISSUE THREAD

**Issue by flik** [waltznetworks/docker-gearman#1]
Status: Downloaded newer image for progrium/consul:latest
Building gearman
ERROR: Cannot locate specified Dockerfile: Dockerfile
I did not copied docker file with docker-compose 
Here is docker-compose:
```
version: '3'

services:
    gearman:
      build:
        context: .
      image: waltznetworks/docker-gearman:latest
      container_name: gearman
      links:
        - consul:consul
      expose:
        - 4730
      ports:
        - 4730:4730
      depends_on:
        - consul

    # service discovery tier
    consul:
      image: progrium/consul:latest
      command: -server -bootstrap -ui-dir /ui
      restart: always
      ports:
        - 8500:8500
      expose:
        - 53
        - 8300
        - 8301
        - 8302
        - 8400
        - 8500
      dns:
        - 127.0.0.1
```
